### ISSUE TITLE
On clicking of remove button in cart page should reload page everytime to see changes

### ISSUE THREAD

**Issue by sathyalog** [sathyalog/ng2-ecommerce#2]
**Add To Cart** and **Remove from Cart** functionalities is working fine as expected. But I found component is not **re-rendering** on removing a product from Cart. Every time we have to **reload** the page to see the changes. Need someone helps to fix this.
<img width="1043" alt="screen shot 2017-01-13 at 4 41 06 pm" src="https://cloud.githubusercontent.com/assets/3416121/21928177/4ba3b1c0-d9af-11e6-98f1-3b09cb3d64de.png">

**Comment by vish288** [comment]
Could you gimme access to the repo pls!

**Comment by vish288** [comment]
Currently the update ensures the cart count is updated but the re-render is an issue here in cart float number too. i am closing this issue with the Update in PR #3 and opening separate issue for re-render.
